services:
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    ports:
      - "127.0.0.1:9092:9092"
    expose:
      - "29092"
    environment:
      CLUSTER_ID: TyCtSFEgSDewVyzlcNNt8A
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://127.0.0.1:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://:9092,CONTROLLER://kafka:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    healthcheck:
      test: "kafka-topics --list --bootstrap-server kafka:29092 | grep elsa-topic"
      interval: 5s
      timeout: 10s
      retries: 5
  init-kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c", "stdbuf -oL /scripts/init_kafka.sh"]
    volumes:
      - ./scripts/init_kafka.sh:/scripts/init_kafka.sh
    healthcheck:
      disable: true
