name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.3.2
          version-type: strict
          elixir-version: 1.14.4
      - name: Get depedencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run unit tests
        run: |
          mix test
  integration:
    name: Integration Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.3
          elixir-version: 1.14.4
      - name: Compose V1 Setup
        run: |
          mkdir "${HOME}/docker-compose"
          cd "${HOME}/docker-compose"
          wget https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64 -O docker-compose
          chmod +x docker-compose
          echo "${HOME}/docker-compose" >> "$GITHUB_PATH"
          echo "docker compose v1 setup complete"
          export PATH="$PWD:$PATH"
        shell: bash
      - name: Get dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run integration tests
        run: |
          mix test.integration
  static:
    name: Static Analysis
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.3
          elixir-version: 1.14.4
      - name: Get dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run formatter
        run: |
          mix format --check-formatted
      - name: Run dialyzer
        run: |
          mix dialyzer
